config/routes.rb
RailsStore::Application.routes.draw do

  
  resources :reviews

  # get '/reviews/new/:id', :to => 'reviews#index', :as => 'reviews'
  # get '/reviews', :to =>'reviews#new', :as => :new_review
  # post '/reviews', :to => 'reviews#create'

  get '/products/cart' => 'products#view_cart', :as => :view_cart

  resources :products
  
  post '/products/:id' => 'products#add_to_cart'
  post '/products/:id/remove' => 'products#remove_from_cart', :as => :remove_from_cart

  root :to => 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :reviews, :body, :in_cart, :image_url

  has_many :reviews,
  :dependent => :destroy
  
  validates_uniqueness_of :name
  validates_presence_of :name
  validates_presence_of :price
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :body, :product_id, :rating, :product
  belongs_to :product

  validates_length_of :body, :minimum => 50, :maximum => 1000
  validates :rating, :inclusion => { :in => 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json

  before_filter :load_products_in_cart
  def load_products_in_cart
    @products_in_cart = Product.where(:in_cart => true)
  end

  before_filter :find_product, :except => [:index, :new, :create, :view_cart]
  def find_product
    @product = Product.find(params[:id])
  end

  def index
    @products = Product.all
    @product = Product.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
    @reviews = Review.where(:product_id => @product.id)
    @products = Product.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @id = params[:id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    respond_to do |format|
      if @product.save
        format.html { redirect_to products_url, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def view_cart
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  def add_to_cart
    @product.update_attributes({:in_cart => true})

    respond_to do |format|
      format.html { redirect_to :back, notice: 'Product was successfully added to cart.' }
      format.json { head :no_content }
    end
  end

   def remove_from_cart
     @product.update_attributes({:in_cart => false})

     respond_to do |format|
       format.html { redirect_to :back, notice: 'Product was successfully removed.' }
       format.json { head :no_content }
     end
   end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_products_in_cart
  def load_products_in_cart
    @products_in_cart = Product.where(:in_cart => true)
  end

  def new
    @review = Review.new
    @product_id = params[:id]
    @product = Product.find(@product_id)
    @products = Product.all

    if @product_id
      @product_name = @products.find{|p| p.id == @product_id.to_i}.name
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  def create
    @review = Review.new(params[:review])
    @products = Product.all
    @product = Product.find(params[:review][:product_id]) 

    respond_to do |format|
      if @review.save
        format.html { redirect_to @product, notice: 'Review was successfully created!' }
        format.json { render json: @review, status: :created, location: @review }
      else
        @product_id = params[:review][:product_id]
        @product = Product.find(@product_id)
        @products = Product.all
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  def price_total
    sum = 0
      @products_in_cart.each do |product|
        sum += product.price
      end 
    number_to_currency(sum)
  end
  
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsStore</title>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">
  <link href='http://fonts.googleapis.com/css?family=Jacques+Francois' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
  	
    <div id="nav">
  	  <h5><%= link_to 'New Product', new_product_path %> 
  	  	/ <%= link_to 'Doggie Bag', view_cart_path %>
        <%= price_total %></h5>
    </div>

  
  	<header>
  	  <h1><%= link_to 'Architecture for Dogs', products_url %></h1>
  	</header>
    <div id="inner_container">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %><br />
  </div>
   <div class="field">
    <%= f.label :description %>
    <%= f.text_area :body %>
  </div>
   <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h3>Editing product</h3>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!-- <div id="nav">
  <h3><%#= link_to 'New Product', new_product_path %></h3>
  <%#= render 'sidecar.html' %>
</div> -->
<%#= link_to 'Product Reviews', reviews_path %>

<!-- <table>
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
  </tr> -->

<% @products.each do |product| %>

  <div class="index_product">
    <%= link_to image_tag(product.image_url), product %>
    <h5><%= link_to product.name, product %> <%= number_to_currency product.price %></h5>
    <span id="buy_button"><%= link_to 'Add to Cart', product, method: :post %></span><br />
    <%#= link_to 'Edit', edit_product_path(product) %>
    <%#= link_to 'Remove', product, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>



<%#= render 'form.html' %>


<%#= link_to 'Add To Cart' %>

app/views/products/new.html.erb
<h3>New product</h3>

<%= render 'form' %>

<%#= link_to 'Back', products_path %>

app/views/products/show.html.erb
<%#= @product.inspect %>

<%#= link_to 'Back', products_path %>

<p id="notice"><%= notice %></p>

<div class="product_image">
<p>
<% if @product.image_url.nil? %>
  <%= image_tag "http://www.mountfanblade.com/style/no_pic.gif" %>
<% else %>
  <img src="<%= @product.image_url %>" >
<% end %>
</p>
</div>


<div class="product_info">
<p>
  <span id="product_name"><%= @product.name %></span>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price %>
</p>

<p>
  <b>Description:</b>
  <%= @product.body %>
</p>


  <div id="buy_button"><%= link_to 'Add to Cart', @product, method: :post %></div><br />
  <div id="edit_button"><%= link_to 'Edit Product', edit_product_path(@product) %></div>
</div>



<div class="reviews">
<h3><a href="/reviews/new?id=<%= @product.id %>">Write a Review</a></h3>
<% @reviews.each do |review| %>
  <div class="review">
      "<% review.rating.round.times do %><i class="icon-star"></i><% end %>"<br />
      <%= review.body %><br />
  </div>
<% end %>
</div>

app/views/products/view_cart.html.erb
<div id="cart">


<span id="your_cart">Doggie Bag:</span><br />
<% @products_in_cart.each do |product| %>
  <%= product.name %> <%= number_to_currency(product.price) %>
  <%= link_to 'Remove', remove_from_cart_url(:id => product.id), method: :post %><br />
<% end %>
  <span id="cart_total">Total <%= price_total %></span>

</div>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :Description %>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %>
    <%= f.select :rating, (0..5) %>
  </div>

  <div class="field">
    <% if @product_id %>
      <input type="hidden" name="review[product_id]" value="<%= @product_id %>"/>
      <%= f.label :product_id %><br />
    <% end %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/new.html.erb
<h3>New review for <%= @product.name %></h3>

<%= render 'form' %>